#!/usr/bin/env bash

REPO=$(grep "NAME" version.go | sed -E "s/.*\"(.+)\"$/\1/")
VERSION=$(grep "VERSION" version.go | sed -E "s/.*\"(.+)\"$/\1/")

ROOT_DIR=$(git rev-parse --show-toplevel)

DIR=$(cd $(dirname ${0})/.. && pwd)
cd ${DIR}

# Run Compile
XC_OS=${XC_OS:-darwin linux windows}

COMMIT=`git describe --always`

rm -rf pkg/
gox \
  -ldflags "-X=main.GitCommit=\"${COMMIT}\"" \
  -os="${XC_OS}" \
  -output "pkg/{{.OS}}_{{.Arch}}/{{.Dir}}"

if [ -d pkg ];then
  rm -rf $ROOT_DIR/pkg/dist
fi

# Package all binary as .zip
mkdir -p $ROOT_DIR/pkg/dist/${VERSION}
for PLATFORM in $(find $ROOT_DIR/pkg -mindepth 1 -maxdepth 1 -type d); do
  PLATFORM_NAME=$(basename ${PLATFORM})
  ARCHIVE_NAME=${REPO}_${VERSION}_${PLATFORM_NAME}
  if [ $PLATFORM_NAME = "dist" ]; then
    continue
  fi
  pushd ${PLATFORM}
  zip -r ${DIR}/pkg/dist/${VERSION}/${ARCHIVE_NAME}.zip ./*
  popd
done

# Generate shasum
cd $ROOT_DIR/pkg/dist/${VERSION}
shasum * > ./${VERSION}_SHASUMS
cd -
