#!/usr/bin/env bash

([ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" == "true" ]) && exit

MERGED_BRANCH=$(git log -n 1 --pretty=format:'%s' | sed -E "s/^Merge pull request #[0-9] from ayatk\/(.+)$/\1/")

if [ $(echo $MERGED_BRANCH | grep -e 'release/v\?[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}') ]; then
    git config --local user.name "ayatk"
    git config --local user.email "git@ayatk.com"
    git tag "$(echo $MERGED_BRANCH | sed -E "s/release\/(.+)$/\1/")"
    git push --quiet https://$GH_TOKEN@github.com/ayatk/memo.git --tags 2> /dev/null
fi
